spring.application.name=ai-service
spring.data.mongodb.uri=mongodb://localhost:27017/airecommendationfitness
spring.data.mongodb.database=airecommendationfitness

spring.config.import=optional:configserver:http://localhost:8888
